server:
  port: 8080

spring:
  rabbitmq:
    addresses: 192.168.16.248:5672
    username: hxrabbit
    password: hx_mq_rabbit_123
    virtual-host: /
    listener:
      type: simple # direct类型是2.0之后才有的
      simple:
        acknowledge-mode: none #manual：手动应答 AUTO：当没有抛出异常时会自动应答